# Generated by Django 6.0.2 on 2026-05-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='partida',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='tiempo',
        ),
        migrations.DeleteModel(
            name='Partida',
        ),
    ]
