# Generated by Django 6.0.2 on 2026-05-15 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_alter_resultado_unique_together_and_more'),
        ('torneos', '0003_alter_torneo_jugadores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='torneos.torneo'),
        ),
        migrations.AlterUniqueTogether(
            name='resultado',
            unique_together={('jugador', 'torneo')},
        ),
    ]
