# Generated by Django 6.0.4 on 2026-05-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0003_resultado_torneo_alter_resultado_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='posicion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
